development:
  adapter: postgresql
  encoding: unicode
  database: rspect
  pool: 5
  username: postgres
  password: postgres

test:
 adapter: postgresql
 encoding: unicode
 database: rspect_test
 pool: 5
 username: postgres
 password: postgres